
from __future__ import annotations
from pathlib import Path
import json, math, shutil, re
from typing import Dict, List, Tuple, Any

from PIL import Image
from .runtime import Runtime
from .extractor import extract_bundle

def _load(path):
    return json.load(open(path, "r", encoding="utf-8"))

def _safe(s):
    s = re.sub(r'[<>:"/\\|?*]+', "_", str(s))
    return s.strip(" .") or "unnamed"

def _frame_time(frame_index, fps):
    """High-precision frame timestamp for exact sampled playback."""
    return round(float(frame_index) / float(max(fps, 1.0)), 9)

def _end_time(frame_count, fps):
    """Animation end after the final sampled frame has displayed for one frame."""
    return round(float(frame_count) / float(max(fps, 1.0)), 9)

def _norm_angle(a):
    a = (float(a) + 180.0) % 360.0 - 180.0
    if abs(a) < 1e-8:
        a = 0.0
    return a


def _affine_to_components(M):
    """
    Exact 2D affine -> Spine-compatible rotation/scale/shear decomposition.

    Important v0.15 change:
    reflections are represented with a SIGNED scaleY instead of forcing
    scaleY positive and encoding the reflection as shearY ~= 180 degrees.

    This produces the same exact matrix, but is far more stable for animation
    interpolation, especially for SS6 parts that use Y-axis 180 degree flips.
    """
    a,b,c,d,tx,ty=[float(x) for x in M]

    sx=math.hypot(a,c)
    rot=math.degrees(math.atan2(c,a)) if sx>=1e-10 else 0.0

    det=a*d-b*c
    sy_mag=math.hypot(b,d)
    sy=sy_mag if det>=0 else -sy_mag

    if sy_mag<1e-10:
        shear_y=0.0
    else:
        actual_y_angle=math.degrees(math.atan2(d,b))
        # A negative scale reverses the Y basis direction by 180 degrees.
        basis_y_angle=actual_y_angle if sy>=0 else actual_y_angle-180.0
        shear_y=_norm_angle(basis_y_angle-rot-90.0)

    return {
        "x":tx,
        "y":ty,
        "rotation":_norm_angle(rot),
        "scaleX":sx,
        "scaleY":sy,
        "shearX":0.0,
        "shearY":shear_y,
    }

def _affine_to_spine_bone(M, name, parent="root"):
    c = _affine_to_components(M)
    out = {"name": name, "parent": parent}
    if abs(c["x"]) > 1e-8: out["x"] = round(c["x"], 6)
    if abs(c["y"]) > 1e-8: out["y"] = round(c["y"], 6)
    if abs(c["rotation"]) > 1e-8: out["rotation"] = round(c["rotation"], 6)
    if abs(c["scaleX"] - 1.0) > 1e-8: out["scaleX"] = round(c["scaleX"], 6)
    if abs(c["scaleY"] - 1.0) > 1e-8: out["scaleY"] = round(c["scaleY"], 6)
    if abs(c["shearY"]) > 1e-8: out["shearY"] = round(c["shearY"], 6)
    return out

def _affine_inv(M):
    a, b, c, d, tx, ty = [float(x) for x in M]
    det = a * d - b * c
    if abs(det) < 1e-12:
        return None
    ia = d / det
    ib = -b / det
    ic = -c / det
    idd = a / det
    itx = -(ia * tx + ib * ty)
    ity = -(ic * tx + idd * ty)
    return (ia, ib, ic, idd, itx, ity)

def _apply(M, x, y):
    a, b, c, d, tx, ty = M
    return (a * x + b * y + tx, c * x + d * y + ty)

def _parse_maps(cellmap_doc):
    if isinstance(cellmap_doc, dict) and isinstance(cellmap_doc.get("maps"), list):
        return cellmap_doc["maps"]
    raise RuntimeError("Expected cellmap.json generated by ss6runtime extract-bundle.")

def _build_regions(maps):
    counts = {}
    for m in maps:
        for c in m.get("cells", []) or []:
            base = str(c.get("plain_name") or c.get("name") or f"cell_{m.get('index',0)}_{c.get('index',0)}")
            counts[base] = counts.get(base, 0) + 1

    regions = {}
    for mi, m in enumerate(maps):
        for ci, c in enumerate(m.get("cells", []) or []):
            base = str(c.get("plain_name") or c.get("name") or f"cell_{mi}_{ci}")
            region = base if counts.get(base, 0) == 1 else f"map{mi}__{base}"
            regions[(int(m.get("index", mi)), int(c.get("index", ci)))] = (region, c, m)
    return regions

def _write_atlas(maps, texture_dir, out_dir, atlas_path):
    texture_dir = Path(texture_dir)
    out_tex = Path(out_dir) / "textures"
    out_tex.mkdir(parents=True, exist_ok=True)

    regions = _build_regions(maps)
    pages = {}
    for mi, m in enumerate(maps):
        tf = m.get("texture_file")
        if not tf:
            pngs = sorted(texture_dir.glob("*.png"))
            if mi < len(pngs):
                tf = pngs[mi].name
        if not tf:
            raise RuntimeError(f"Could not resolve texture file for cellmap {mi}")
        src = texture_dir / tf
        if not src.exists():
            raise FileNotFoundError(src)
        dst = out_tex / src.name
        if src.resolve() != dst.resolve():
            shutil.copy2(src, dst)
        with Image.open(src) as im:
            size = (im.width, im.height)
        pages[int(m.get("index", mi))] = {"file": src.name, "size": size}

    lines = []
    emitted = set()
    for mi, m in enumerate(maps):
        map_index = int(m.get("index", mi))
        page = pages[map_index]
        if map_index not in emitted:
            if lines:
                lines.append("")
            lines.extend([
                f"textures/{page['file']}",
                f"size: {page['size'][0]},{page['size'][1]}",
                "format: RGBA8888",
                "filter: Linear,Linear",
                "repeat: none",
            ])
            emitted.add(map_index)

        for ci, c in enumerate(m.get("cells", []) or []):
            key = (map_index, int(c.get("index", ci)))
            region, _, _ = regions[key]
            x = int(round(float(c.get("x", 0))))
            y = int(round(float(c.get("y", 0))))
            w = int(round(float(c.get("width", 0))))
            h = int(round(float(c.get("height", 0))))
            lines.extend([
                region,
                "  rotate: false",
                f"  xy: {x}, {y}",
                f"  size: {w}, {h}",
                f"  orig: {w}, {h}",
                "  offset: 0, 0",
                "  index: -1",
            ])
    Path(atlas_path).write_text("\n".join(lines) + "\n", encoding="utf-8")
    return regions, pages

def _uvs_from_ss6(uv_rows, flip_v=False):
    out = []
    for uv in uv_rows or []:
        if isinstance(uv, dict):
            u = float(uv.get("x", 0))
            v = float(uv.get("y", 0))
        elif isinstance(uv, (list, tuple)) and len(uv) >= 2:
            u = float(uv[0]); v = float(uv[1])
        else:
            continue
        if flip_v:
            v = 1.0 - v
        out.extend([round(u, 8), round(v, 8)])
    return out

def _rgba_hex(alpha01):
    a = max(0, min(255, round(float(alpha01) * 255)))
    return f"ffffff{a:02x}"

def _part_key_to_cell(part):
    cell = part.get("cell")
    if not isinstance(cell, dict):
        return None
    return (int(cell.get("IndexCellMap", -1)), int(cell.get("IndexCell", -1)))

def _part_visible(part, regions, show_hidden=False):
    if (not show_hidden) and bool(part.get("hidden_provisional", False)):
        return False
    return _part_key_to_cell(part) in regions

def _region_attachment_from_cell(region_name, cell):
    w = float(cell.get("width", 0))
    h = float(cell.get("height", 0))
    piv = cell.get("pivot", {}) or {}
    px = float(piv.get("x", w / 2))
    py = float(piv.get("y", h / 2))
    local_x = w / 2.0 - px
    local_y = py - h / 2.0
    att = {"path": region_name, "width": w, "height": h}
    if abs(local_x) > 1e-8:
        att["x"] = round(local_x, 6)
    if abs(local_y) > 1e-8:
        att["y"] = round(local_y, 6)
    return att

def _mesh_attachment_from_part(part, region_name, cell, mesh_v_flip=False):
    mesh = part.get("skinned_mesh")
    M = part.get("world_affine")
    if not (isinstance(mesh, dict) and mesh.get("vertices") and mesh.get("triangles") and M):
        return None, "missing mesh geometry"

    inv = _affine_inv(M)
    if inv is None:
        return None, "singular part transform"

    localverts = []
    for v in mesh["vertices"]:
        x, y = _apply(inv, float(v["x"]), float(v["y"]))
        localverts.extend([round(x, 6), round(y, 6)])

    uvs = _uvs_from_ss6(mesh.get("uv", []), mesh_v_flip)
    triangles = [int(x) for x in (mesh.get("triangles", []) or [])]
    vertex_count = len(localverts) // 2

    att = {
        "type": "mesh",
        "path": region_name,
        "uvs": uvs,
        "triangles": triangles,
        "vertices": localverts,
        "hull": vertex_count,
        "width": float(cell.get("width", 0)),
        "height": float(cell.get("height", 0)),
    }
    return att, None

def _eval_all_frames(rt):
    return [rt.evaluate_frame(i, "native2d", "zxy") for i in range(int(rt.frame_count))]

def _build_static_setup(frames, maps, regions, frame0_index=0, mesh_v_flip=False, show_hidden=False):
    state0 = frames[frame0_index]
    parts0 = state0["parts"]
    bones = [{"name": "root"}]
    slots = []
    attachments = {}
    slot_order = []
    part_to_slot = {}
    slot_meta = {}
    warnings = []
    region_count = 0
    mesh_count = 0

    for p in parts0:
        M = p.get("world_affine")
        if M:
            bones.append(_affine_to_spine_bone(M, str(p["name"]), "root"))

    drawable = []
    for p in parts0:
        key = _part_key_to_cell(p)
        if key is None or key not in regions:
            continue
        if (not show_hidden) and bool(p.get("hidden_provisional", False)):
            continue
        drawable.append(p)
    drawable.sort(key=lambda p: (int(p.get("priority", 0) or 0), int(p.get("index", 0))))

    # Gather every attachment actually used by each slot across all frames.
    used_cells = {}
    for state in frames:
        by_index = {int(pp["index"]): pp for pp in state["parts"]}
        for p0 in drawable:
            idx = int(p0["index"])
            p = by_index.get(idx)
            if not p:
                continue
            key = _part_key_to_cell(p)
            if key is None or key not in regions:
                continue
            used_cells.setdefault(idx, [])
            if key not in used_cells[idx]:
                used_cells[idx].append(key)

    for p in drawable:
        idx = int(p["index"])
        pname = str(p["name"])
        slot_name = pname
        part_to_slot[idx] = slot_name
        slot_order.append(slot_name)

        key0 = _part_key_to_cell(p)
        region_name0, cell0, _ = regions[key0]

        slots.append({"name": slot_name, "bone": pname, "attachment": slot_name})
        opacity = p.get("opacity", 1.0)
        if isinstance(opacity, (int, float)) and float(opacity) < 0.9999:
            slots[-1]["color"] = _rgba_hex(opacity)

        attachments[slot_name] = {}
        attach_names = {}

        keys_for_slot = used_cells.get(idx, [key0])
        for j, key in enumerate(keys_for_slot):
            region_name, cell, _map = regions[key]
            attach_name = slot_name if key == key0 else f"{slot_name}__{region_name}"
            frame_part = None
            for state in frames:
                by_index = {int(pp["index"]): pp for pp in state["parts"]}
                pp = by_index.get(idx)
                if pp and _part_key_to_cell(pp) == key:
                    frame_part = pp
                    break

            if frame_part and isinstance(frame_part.get("skinned_mesh"), dict) and frame_part["skinned_mesh"].get("vertices"):
                att, err = _mesh_attachment_from_part(frame_part, region_name, cell, mesh_v_flip=mesh_v_flip)
                if att is not None:
                    attachments[slot_name][attach_name] = att
                    mesh_count += 1
                else:
                    warnings.append(f"{slot_name}: mesh attachment fallback to region for {attach_name} ({err})")
                    attachments[slot_name][attach_name] = _region_attachment_from_cell(region_name, cell)
                    region_count += 1
            else:
                attachments[slot_name][attach_name] = _region_attachment_from_cell(region_name, cell)
                region_count += 1
            attach_names[key] = attach_name

        slot_meta[slot_name] = {
            "part_index": idx,
            "setup_cell_key": key0,
            "attachment_names": attach_names,
            "setup_attachment": slot_name,
            "setup_is_mesh": slot_name in attachments and isinstance(attachments[slot_name].get(slot_name), dict) and attachments[slot_name][slot_name].get("type") == "mesh"
        }

    return {
        "bones": bones,
        "slots": slots,
        "attachments": attachments,
        "slot_order": slot_order,
        "part_to_slot": part_to_slot,
        "slot_meta": slot_meta,
        "warnings": warnings,
        "region_attachments": region_count,
        "mesh_attachments": mesh_count,
    }

def _timeline_changed(prev, cur, tol=1e-8):
    if prev is None:
        return True
    if isinstance(cur, dict):
        keys = set(prev.keys()) | set(cur.keys())
        for k in keys:
            pv = prev.get(k)
            cv = cur.get(k)
            if isinstance(cv, (int, float)) or isinstance(pv, (int, float)):
                if abs(float(pv or 0.0) - float(cv or 0.0)) > tol:
                    return True
            else:
                if pv != cv:
                    return True
        return False
    return prev != cur


def _unwrap_delta(value, reference, previous_delta=None):
    """Return value-reference, choosing the 360-degree equivalent nearest previous_delta."""
    d=float(value)-float(reference)
    while d > 180.0:
        d -= 360.0
    while d <= -180.0:
        d += 360.0
    if previous_delta is not None:
        while d - previous_delta > 180.0:
            d -= 360.0
        while d - previous_delta < -180.0:
            d += 360.0
    return d

def _setup_components_by_bone(setup_data):
    out={}
    for b in setup_data["bones"]:
        if b["name"]=="root":
            continue
        out[b["name"]]={
            "x":float(b.get("x",0.0)),
            "y":float(b.get("y",0.0)),
            "rotation":float(b.get("rotation",0.0)),
            "scaleX":float(b.get("scaleX",1.0)),
            "scaleY":float(b.get("scaleY",1.0)),
            "shearX":float(b.get("shearX",0.0)),
            "shearY":float(b.get("shearY",0.0)),
        }
    return out


def _build_deform_data(rt, frames, regions, setup_data):
    """
    Build Spine deform timelines for the unweighted mesh attachments emitted by this exporter.

    The setup mesh stores local x,y vertices. At each frame:
      runtime skinned world vertices
        -> inverse(current flat bone world affine)
        -> current mesh vertices in Spine bone-local space
        -> subtract setup mesh vertices
        -> Spine deform delta

    JSON shape:
      deform -> default -> slot -> attachment -> [keyframes]
    """
    fps=float(max(rt.fps,1.0))
    deform_skin={}
    warnings=[]
    timeline_count=0
    keyframe_count=0

    for slot_name, meta in setup_data["slot_meta"].items():
        idx=int(meta["part_index"])
        slot_atts=setup_data["attachments"].get(slot_name,{})
        if not slot_atts:
            continue

        for cell_key, attach_name in meta["attachment_names"].items():
            setup_att=slot_atts.get(attach_name)
            if not isinstance(setup_att,dict) or setup_att.get("type")!="mesh":
                continue

            setup_vertices=setup_att.get("vertices",[]) or []
            if len(setup_vertices)%2!=0 or not setup_vertices:
                warnings.append(f"{slot_name}/{attach_name}: invalid setup mesh vertices")
                continue
            vertex_count=len(setup_vertices)//2

            keys=[]
            prev_delta=None

            for fi,state in enumerate(frames):
                by_index={int(p["index"]):p for p in state["parts"]}
                p=by_index.get(idx)
                if not p or _part_key_to_cell(p)!=cell_key:
                    continue

                mesh=p.get("skinned_mesh")
                M=p.get("world_affine")
                if not (isinstance(mesh,dict) and mesh.get("vertices") and M):
                    continue
                verts=mesh["vertices"]
                if len(verts)!=vertex_count:
                    warnings.append(
                        f"{slot_name}/{attach_name}: frame {fi} vertex count {len(verts)} != setup {vertex_count}"
                    )
                    continue

                inv=_affine_inv(M)
                if inv is None:
                    warnings.append(f"{slot_name}/{attach_name}: frame {fi} singular bone matrix")
                    continue

                delta=[]
                for vi,v in enumerate(verts):
                    lx,ly=_apply(inv,float(v["x"]),float(v["y"]))
                    dx=lx-float(setup_vertices[2*vi])
                    dy=ly-float(setup_vertices[2*vi+1])
                    # suppress tiny floating-point noise
                    if abs(dx)<1e-6: dx=0.0
                    if abs(dy)<1e-6: dy=0.0
                    delta.extend([round(dx,6),round(dy,6)])

                # Always retain per-frame keys while the attachment is active.
                # This matches the runtime's already-sampled frame states.
                key={"time":_frame_time(fi,fps)}
                if any(abs(v)>1e-8 for v in delta):
                    key["vertices"]=delta
                keys.append(key)
                keyframe_count+=1
                prev_delta=delta

            if keys:
                deform_skin.setdefault(slot_name,{})[attach_name]=keys
                timeline_count+=1

    return ({"default":deform_skin} if deform_skin else {}), warnings, timeline_count, keyframe_count


def _all_close(vals, default, tol=1e-6):
    return all(abs(float(v)-float(default))<=tol for v in vals)

def _key_values(k, fields):
    return tuple(float(k.get(f,0.0)) for f in fields)

def _simplify_linear_keys(keys, fields, tol=1e-5):
    """
    Remove middle samples that lie on the straight line between their neighbors.
    This preserves the same linear interpolation while greatly reducing dense
    per-frame sampled SS6 timelines.
    """
    if len(keys)<=2:
        return keys
    out=[keys[0]]
    for i in range(1,len(keys)-1):
        a=out[-1]
        b=keys[i]
        c=keys[i+1]
        ta=float(a.get("time",0)); tb=float(b.get("time",0)); tc=float(c.get("time",0))
        if tc-ta<=1e-12:
            out.append(b); continue
        r=(tb-ta)/(tc-ta)
        av=_key_values(a,fields); bv=_key_values(b,fields); cv=_key_values(c,fields)
        predicted=tuple(x+r*(z-x) for x,z in zip(av,cv))
        if any(abs(y-p)>tol for y,p in zip(bv,predicted)):
            out.append(b)
    out.append(keys[-1])
    return out

def _matrix_from_components(c):
    rot=math.radians(float(c["rotation"]))
    ay=math.radians(float(c["rotation"])+90.0+float(c["shearY"]))
    sx=float(c["scaleX"]); sy=float(c["scaleY"])
    return (
        math.cos(rot)*sx,
        math.cos(ay)*sy,
        math.sin(rot)*sx,
        math.sin(ay)*sy,
        float(c["x"]),
        float(c["y"])
    )

def _selfcheck_flat_bones(frames, setup_data):
    """
    Verify that our setup + relative animation channels reconstruct the Python
    runtime world affine matrices at frame samples.
    """
    setup=_setup_components_by_bone(setup_data)
    max_err=0.0
    worst=None
    for fi,state in enumerate(frames):
        by_name={str(p["name"]):p for p in state["parts"]}
        for bn,base in setup.items():
            p=by_name.get(bn)
            if not p or not p.get("world_affine"): continue
            cur=_affine_to_components(p["world_affine"])
            # Relative timeline semantics at an exact sample.
            comp={
                "x":base["x"]+(cur["x"]-base["x"]),
                "y":base["y"]+(cur["y"]-base["y"]),
                "rotation":base["rotation"]+_unwrap_delta(cur["rotation"],base["rotation"]),
                "scaleX":base["scaleX"]*((cur["scaleX"]/base["scaleX"]) if abs(base["scaleX"])>1e-12 else 1.0),
                "scaleY":base["scaleY"]*((cur["scaleY"]/base["scaleY"]) if abs(base["scaleY"])>1e-12 else 1.0),
                "shearY":base["shearY"]+_unwrap_delta(cur["shearY"],base["shearY"]),
            }
            R=_matrix_from_components(comp)
            M=p["world_affine"]
            e=max(abs(float(a)-float(b)) for a,b in zip(M,R))
            if e>max_err:
                max_err=e;worst={"frame":fi,"bone":bn,"error":e}
    return {"max_matrix_error":max_err,"worst":worst}

def _build_animation_data(rt, frames, regions, setup_data, show_hidden=False):
    """
    Spine bone animation keys are RELATIVE TO THE SETUP POSE.

    translate: frame_position - setup_position
    rotate:    frame_rotation - setup_rotation
    scale:     frame_scale / setup_scale
    shear:     frame_shear - setup_shear

    The previous v0.12 exporter incorrectly wrote absolute evaluated values here.
    """
    fps=float(max(rt.fps,1.0))
    anim_name=str(frames[0].get("animation") or "anim_0")
    setup_comp=_setup_components_by_bone(setup_data)
    bone_names=list(setup_comp.keys())

    bones_tl={bn:{"translate":[],"rotate":[],"scale":[],"shear":[]} for bn in bone_names}
    slots_tl={}
    setup_order=list(setup_data["slot_order"])
    draworder_changes=[]
    warnings=[]

    prev_draw=list(setup_order)
    current_attachment_by_slot={s["name"]:s.get("attachment") for s in setup_data["slots"]}
    setup_slot_color={s["name"]:s.get("color","ffffffff") for s in setup_data["slots"]}
    prev_slot_state={
        s["name"]:{
            "attachment":s.get("attachment"),
            "color":s.get("color","ffffffff")
        } for s in setup_data["slots"]
    }
    prev_rot_delta={bn:None for bn in bone_names}
    prev_shear_delta={bn:None for bn in bone_names}

    # Cache part lookup by name for each frame.
    frame_by_name=[]
    for state in frames:
        frame_by_name.append({str(p["name"]):p for p in state["parts"]})

    for fi,state in enumerate(frames):
        t=_frame_time(fi,fps)
        by_name=frame_by_name[fi]

        # Bone timelines, relative to setup pose.
        for bn in bone_names:
            p=by_name.get(bn)
            if not p or not p.get("world_affine"):
                continue

            cur=_affine_to_components(p["world_affine"])
            base=setup_comp[bn]

            tx=cur["x"]-base["x"]
            ty=cur["y"]-base["y"]

            rd=_unwrap_delta(cur["rotation"],base["rotation"],prev_rot_delta[bn])
            prev_rot_delta[bn]=rd

            sx_base=base["scaleX"]
            sy_base=base["scaleY"]
            sx=(cur["scaleX"]/sx_base) if abs(sx_base)>1e-12 else 1.0
            sy=(cur["scaleY"]/sy_base) if abs(sy_base)>1e-12 else 1.0

            shy=_unwrap_delta(cur["shearY"],base["shearY"],prev_shear_delta[bn])
            prev_shear_delta[bn]=shy

            bones_tl[bn]["translate"].append({
                "time":t,
                "x":round(tx,6),
                "y":round(ty,6)
            })
            bones_tl[bn]["rotate"].append({
                "time":t,
                "angle":round(rd,6)
            })
            bones_tl[bn]["scale"].append({
                "time":t,
                "x":round(sx,6),
                "y":round(sy,6)
            })
            bones_tl[bn]["shear"].append({
                "time":t,
                "x":0.0,
                "y":round(shy,6)
            })

        # Slots.
        current_order_parts=[]
        by_index={int(p["index"]):p for p in state["parts"]}
        for idx,slot_name in setup_data["part_to_slot"].items():
            p=by_index.get(int(idx))
            if not p:
                continue

            key=_part_key_to_cell(p)
            visible=_part_visible(p,regions,show_hidden=show_hidden)
            meta=setup_data["slot_meta"][slot_name]
            attach_name=meta["attachment_names"].get(key,current_attachment_by_slot.get(slot_name))
            alpha=0.0 if not visible else float(
                p.get("opacity",1.0) if isinstance(p.get("opacity",1.0),(int,float)) else 1.0
            )

            cur_state={"attachment":attach_name,"color":_rgba_hex(alpha)}
            prev=prev_slot_state.get(slot_name)
            if slot_name not in slots_tl:
                slots_tl[slot_name]={}

            if prev is None or prev.get("attachment")!=cur_state["attachment"]:
                keyframe={"time":t}
                if cur_state["attachment"] is not None:
                    keyframe["name"]=cur_state["attachment"]
                slots_tl[slot_name].setdefault("attachment",[]).append(keyframe)
                current_attachment_by_slot[slot_name]=cur_state["attachment"]

            if prev is None or prev.get("color")!=cur_state["color"]:
                slots_tl[slot_name].setdefault("color",[]).append({
                    "time":t,
                    "color":cur_state["color"]
                })

            prev_slot_state[slot_name]=cur_state
            current_order_parts.append((
                int(p.get("priority",0) or 0),
                int(p.get("index",0)),
                slot_name
            ))

        # Dynamic draw order.
        current_order=[sn for _,_,sn in sorted(current_order_parts)]
        if current_order and current_order!=prev_draw:
            if fi>0:
                offsets=[]
                # Spine offsets are relative to setup order.
                for current_i,slot_name in enumerate(current_order):
                    if slot_name not in setup_order:
                        continue
                    setup_i=setup_order.index(slot_name)
                    off=current_i-setup_i
                    if off!=0:
                        offsets.append({"slot":slot_name,"offset":off})
                if offsets:
                    draworder_changes.append({"time":t,"offsets":offsets})
            prev_draw=current_order

    # v0.15: omit channels that are identical to setup for the entire clip,
    # and remove redundant linear samples from channels that do change.
    bones_block={}
    for bn,tl in bones_tl.items():
        item={}

        if tl["translate"]:
            xs=[k["x"] for k in tl["translate"]]; ys=[k["y"] for k in tl["translate"]]
            if not (_all_close(xs,0.0) and _all_close(ys,0.0)):
                item["translate"]=_simplify_linear_keys(tl["translate"],("x","y"))

        if tl["rotate"]:
            vals=[k["angle"] for k in tl["rotate"]]
            if not _all_close(vals,0.0):
                item["rotate"]=_simplify_linear_keys(tl["rotate"],("angle",))

        if tl["scale"]:
            xs=[k["x"] for k in tl["scale"]]; ys=[k["y"] for k in tl["scale"]]
            if not (_all_close(xs,1.0) and _all_close(ys,1.0)):
                item["scale"]=_simplify_linear_keys(tl["scale"],("x","y"))

        if tl["shear"]:
            xs=[k["x"] for k in tl["shear"]]; ys=[k["y"] for k in tl["shear"]]
            if not (_all_close(xs,0.0) and _all_close(ys,0.0)):
                item["shear"]=_simplify_linear_keys(tl["shear"],("x","y"))

        if item:
            bones_block[bn]=item

    slots_block={}
    for sn,tl in slots_tl.items():
        item={}
        for k in ("attachment","color"):
            if tl.get(k):
                item[k]=tl[k]
        if item:
            slots_block[sn]=item

    anim={"bones":bones_block}
    if slots_block:
        anim["slots"]=slots_block
    if draworder_changes:
        anim["draworder"]=draworder_changes

    deform_block,deform_warnings,deform_timeline_count,deform_keyframe_count=_build_deform_data(
        rt,frames,regions,setup_data
    )
    if deform_block:
        anim["deform"]=deform_block
    warnings.extend(deform_warnings)

    return anim_name,anim,warnings,deform_timeline_count,deform_keyframe_count

def _build_static_doc_and_setup(rt, maps, regions, texture_dir, out, name, frame, mesh_v_flip=False, show_hidden=False):
    frames = _eval_all_frames(rt)
    setup_data = _build_static_setup(frames, maps, regions, frame0_index=int(frame), mesh_v_flip=mesh_v_flip, show_hidden=show_hidden)
    skeleton_name = _safe(name or Path(out).name or "ss6_character")
    atlas_path = out / f"{skeleton_name}.atlas"
    _write_atlas(maps, texture_dir, out, atlas_path)

    doc = {
        "skeleton": {
            "spine": "4.2.00",
            "images": "./textures/",
            "ss6Runtime": "ss6python_runtime_v15",
            "ss6Animation": str(frames[0].get("animation", "")),
            "ss6Frame": int(frame),
            "ss6Mode": "native2d-yup-flatworld"
        },
        "bones": setup_data["bones"],
        "slots": setup_data["slots"],
        "skins": [{"name": "default", "attachments": setup_data["attachments"]}],
        "animations": {
            "setup": {
                "bones": {
                    "root": {
                        "rotate": [{"time": 0.0, "angle": 0.0}]
                    }
                }
            }
        }
    }
    return doc, frames, setup_data, atlas_path

def export_spine_static(parts_raw_path, animation_raw_path, cellmap_path, texture_dir,
                        output_dir, frame=0, name=None, mesh_v_flip=False, show_hidden=False):
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    rt = Runtime.from_files(parts_raw_path, animation_raw_path)
    maps = _parse_maps(_load(cellmap_path))
    regions = _build_regions(maps)

    doc, frames, setup_data, atlas_path = _build_static_doc_and_setup(
        rt, maps, regions, texture_dir, out, name, frame, mesh_v_flip=mesh_v_flip, show_hidden=show_hidden
    )

    skeleton_name = _safe(name or Path(output_dir).name or "ss6_character")
    json_path = out / f"{skeleton_name}.json"
    json_path.write_text(json.dumps(doc, ensure_ascii=False, indent=2), encoding="utf-8")

    report = {
        "json": str(json_path),
        "atlas": str(atlas_path),
        "textures_dir": str(out / "textures"),
        "frame": int(frame),
        "animation": frames[0].get("animation"),
        "bones": len(doc["bones"]),
        "slots": len(doc["slots"]),
        "region_attachments": setup_data["region_attachments"],
        "mesh_attachments": setup_data["mesh_attachments"],
        "mesh_v_flip": bool(mesh_v_flip),
        "show_hidden": bool(show_hidden),
        "placeholder_animation": "setup",
        "warnings": setup_data["warnings"],
    }
    (out / "spine_export_report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    return report

def export_spine_animated(parts_raw_path, animation_raw_path, cellmap_path, texture_dir,
                          output_dir, setup_frame=0, name=None, mesh_v_flip=False, show_hidden=False):
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    rt = Runtime.from_files(parts_raw_path, animation_raw_path)
    maps = _parse_maps(_load(cellmap_path))
    regions = _build_regions(maps)

    doc, frames, setup_data, atlas_path = _build_static_doc_and_setup(
        rt, maps, regions, texture_dir, out, name, setup_frame, mesh_v_flip=mesh_v_flip, show_hidden=show_hidden
    )

    anim_name, anim_block, anim_warnings, deform_timeline_count, deform_keyframe_count = _build_animation_data(
        rt, frames, regions, setup_data, show_hidden=show_hidden
    )
    doc["animations"][anim_name] = anim_block
    doc["skeleton"]["ss6Animation"] = anim_name
    doc["skeleton"]["ss6Frame"] = int(setup_frame)

    skeleton_name = _safe(name or Path(output_dir).name or "ss6_character")
    json_path = out / f"{skeleton_name}.json"
    json_path.write_text(json.dumps(doc, ensure_ascii=False, indent=2), encoding="utf-8")

    selfcheck=_selfcheck_flat_bones(frames,setup_data)
    bone_timeline_count=sum(len(v) for v in anim_block.get("bones",{}).values())
    bone_keyframe_count=sum(len(keys) for v in anim_block.get("bones",{}).values() for keys in v.values())
    slot_timeline_count=sum(len(v) for v in anim_block.get("slots",{}).values())
    slot_keyframe_count=sum(len(keys) for v in anim_block.get("slots",{}).values() for keys in v.values())

    report = {
        "json": str(json_path),
        "atlas": str(atlas_path),
        "textures_dir": str(out / "textures"),
        "setup_frame": int(setup_frame),
        "animation": anim_name,
        "frame_count": int(rt.frame_count),
        "fps": float(rt.fps),
        "bone_timelines":bone_timeline_count,
        "bone_keyframes":bone_keyframe_count,
        "slot_timelines":slot_timeline_count,
        "slot_keyframes":slot_keyframe_count,
        "transform_selfcheck":selfcheck,
        "bones": len(doc["bones"]),
        "slots": len(doc["slots"]),
        "region_attachments": setup_data["region_attachments"],
        "mesh_attachments": setup_data["mesh_attachments"],
        "mesh_animation_supported": True,
        "mesh_animation_mode":"baked-unweighted-deform",
        "deform_timelines":deform_timeline_count,
        "deform_keyframes":deform_keyframe_count,
        "timeline_transform_semantics":"relative-to-setup",
        "exported_animations": ["setup", anim_name],
        "mesh_v_flip": bool(mesh_v_flip),
        "show_hidden": bool(show_hidden),
        "warnings": setup_data["warnings"] + anim_warnings,
    }
    (out / "spine_export_report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    return report

def bundle_to_spine_static(bundle_path, output_dir, frame=0, name=None,
                           animation_name=None, animation_index=None, data_animation=None,
                           root_path_id=None, mesh_v_flip=False, show_hidden=False):
    out = Path(output_dir)
    extracted = out / "_extracted"
    extract_bundle(
        bundle_path, extracted,
        animation_name=animation_name,
        animation_index=animation_index,
        data_animation=data_animation,
        root_path_id=root_path_id,
        all_animations=False
    )
    result = export_spine_static(
        extracted / "parts_raw.json",
        extracted / "animation_raw.json",
        extracted / "cellmap.json",
        extracted / "textures",
        out,
        frame=frame,
        name=name or _safe(Path(bundle_path).stem),
        mesh_v_flip=mesh_v_flip,
        show_hidden=show_hidden
    )
    result["extract_manifest"] = str(extracted / "extract_manifest.json")
    return result

def bundle_to_spine_animated(bundle_path, output_dir, setup_frame=0, name=None,
                             animation_name=None, animation_index=None, data_animation=None,
                             root_path_id=None, mesh_v_flip=False, show_hidden=False):
    out = Path(output_dir)
    extracted = out / "_extracted"
    extract_bundle(
        bundle_path, extracted,
        animation_name=animation_name,
        animation_index=animation_index,
        data_animation=data_animation,
        root_path_id=root_path_id,
        all_animations=False
    )
    result = export_spine_animated(
        extracted / "parts_raw.json",
        extracted / "animation_raw.json",
        extracted / "cellmap.json",
        extracted / "textures",
        out,
        setup_frame=setup_frame,
        name=name or _safe(Path(bundle_path).stem),
        mesh_v_flip=mesh_v_flip,
        show_hidden=show_hidden
    )
    result["extract_manifest"] = str(extracted / "extract_manifest.json")
    return result


# ---------------------------------------------------------------------------
# v0.16 baked-visual exporter
# ---------------------------------------------------------------------------

def _quad_world_vertices(part, cell):
    """Return 4 world-space vertices matching the preview renderer's Y-up cell geometry."""
    M=part.get("world_affine")
    if not M:
        return None
    w=float(cell.get("width",0)); h=float(cell.get("height",0))
    piv=cell.get("pivot",{}) or {}
    px=float(piv.get("x",w/2)); py=float(piv.get("y",h/2))
    loc=[
        (-px, py),
        (w-px, py),
        (w-px, py-h),
        (-px, py-h),
    ]
    out=[]
    for x,y in loc:
        q=_apply(M,x,y)
        out.extend([round(q[0],6),round(q[1],6)])
    return out

def _part_world_geometry(part, cell, mesh_v_flip=False):
    """
    Return (vertices, uvs, triangles) in ROOT/world coordinates.

    All exported baked attachments live directly on the Spine root bone, so
    world coordinates from the Python runtime are also attachment-local coords.
    """
    mesh=part.get("skinned_mesh")
    if isinstance(mesh,dict) and mesh.get("vertices") and mesh.get("triangles"):
        verts=[]
        for v in mesh["vertices"]:
            verts.extend([round(float(v["x"]),6),round(float(v["y"]),6)])
        uvs=_uvs_from_ss6(mesh.get("uv",[]),mesh_v_flip)
        triangles=[int(x) for x in (mesh.get("triangles",[]) or [])]
        return verts,uvs,triangles

    verts=_quad_world_vertices(part,cell)
    if verts is None:
        return None,None,None
    # Region-local UVs for a full rectangular atlas region.
    if mesh_v_flip:
        uvs=[0.0,1.0, 1.0,1.0, 1.0,0.0, 0.0,0.0]
    else:
        uvs=[0.0,0.0, 1.0,0.0, 1.0,1.0, 0.0,1.0]
    triangles=[0,1,2, 2,3,0]
    return verts,uvs,triangles

def _trim_zero_deform(delta,tol=1e-7):
    """
    Spine deform supports offset + partial vertex arrays.
    Trim leading/trailing zero scalars to shrink JSON substantially.
    """
    first=None;last=None
    for i,v in enumerate(delta):
        if abs(float(v))>tol:
            first=i;break
    if first is None:
        return None,None
    for i in range(len(delta)-1,-1,-1):
        if abs(float(delta[i]))>tol:
            last=i;break
    return first,[round(float(x),6) for x in delta[first:last+1]]

def export_spine_baked(parts_raw_path,animation_raw_path,cellmap_path,texture_dir,
                       output_dir,setup_frame=0,name=None,mesh_v_flip=False,
                       show_hidden=False,stepped=False):
    """
    Fidelity-first exporter.

    Instead of exporting 100+ animated bones, every visible SS6 part is converted
    to an unweighted Spine mesh attached directly to root. Its final evaluated
    world vertices are then baked into a deform timeline.

    This bypasses Spine transform decomposition/interpolation completely.
    """
    out=Path(output_dir);out.mkdir(parents=True,exist_ok=True)
    rt=Runtime.from_files(parts_raw_path,animation_raw_path)
    frames=_eval_all_frames(rt)
    maps=_parse_maps(_load(cellmap_path))
    regions=_build_regions(maps)

    skeleton_name=_safe(name or Path(output_dir).name or "ss6_character")
    atlas_path=out/f"{skeleton_name}.atlas"
    _write_atlas(maps,texture_dir,out,atlas_path)

    # Stable visual-part list: any part that has a known cell in any frame.
    visual_indices=[]
    part_names={}
    used_cells={}
    for state in frames:
        for p in state["parts"]:
            idx=int(p["index"])
            key=_part_key_to_cell(p)
            if key is None or key not in regions:
                continue
            part_names[idx]=str(p["name"])
            if idx not in visual_indices:
                visual_indices.append(idx)
            used_cells.setdefault(idx,[])
            if key not in used_cells[idx]:
                used_cells[idx].append(key)

    # Setup draw order from selected setup frame.
    sf=frames[int(setup_frame)]
    sf_by_index={int(p["index"]):p for p in sf["parts"]}
    ordered=[]
    for idx in visual_indices:
        p=sf_by_index.get(idx)
        if p:
            ordered.append((int(p.get("priority",0) or 0),idx))
        else:
            ordered.append((0,idx))
    ordered.sort()
    visual_indices=[idx for _,idx in ordered]

    bones=[{"name":"root"}]
    slots=[]
    attachments={}
    meta={}
    warnings=[]

    # Build every cell attachment using the FIRST frame in which that cell is active.
    for idx in visual_indices:
        slot=part_names[idx]
        attachments[slot]={}
        attach_names={}

        setup_part=sf_by_index.get(idx)
        setup_key=_part_key_to_cell(setup_part) if setup_part else None
        setup_attachment=None

        for cell_key in used_cells.get(idx,[]):
            region_name,cell,_=regions[cell_key]
            source_part=None
            source_frame=None
            for fi,state in enumerate(frames):
                byidx={int(p["index"]):p for p in state["parts"]}
                p=byidx.get(idx)
                if p and _part_key_to_cell(p)==cell_key:
                    source_part=p;source_frame=fi;break
            if source_part is None:
                continue

            verts,uvs,tris=_part_world_geometry(source_part,cell,mesh_v_flip=mesh_v_flip)
            if not verts:
                warnings.append(f"{slot}: could not build geometry for cell {cell_key}")
                continue

            aname=slot if cell_key==setup_key else f"{slot}__{region_name}"
            attachments[slot][aname]={
                "type":"mesh",
                "path":region_name,
                "uvs":uvs,
                "triangles":tris,
                "vertices":verts,
                "hull":len(verts)//2,
                "width":float(cell.get("width",0)),
                "height":float(cell.get("height",0)),
            }
            attach_names[cell_key]=aname
            if cell_key==setup_key:
                setup_attachment=aname

        # If setup frame has no active cell, use first known attachment but hide slot.
        if setup_attachment is None and attach_names:
            setup_attachment=next(iter(attach_names.values()))

        s={"name":slot,"bone":"root"}
        if setup_attachment is not None:
            s["attachment"]=setup_attachment

        visible=False
        alpha=1.0
        if setup_part:
            visible=_part_visible(setup_part,regions,show_hidden=show_hidden)
            alpha=float(setup_part.get("opacity",1.0) if isinstance(setup_part.get("opacity",1.0),(int,float)) else 1.0)
        if not visible:
            alpha=0.0
        if alpha<0.9999:
            s["color"]=_rgba_hex(alpha)
        slots.append(s)

        meta[slot]={
            "part_index":idx,
            "attachment_names":attach_names,
            "setup_attachment":setup_attachment,
        }

    # Build animation.
    anim_name=str(frames[0].get("animation") or "animation")
    fps=float(max(rt.fps,1.0))
    deform_skin={}
    slot_tl={}
    draworder=[]
    deform_keys=0

    prev_slot={}
    prev_order=[s["name"] for s in slots]

    # Cache attachment setup vertices.
    setup_vertices={}
    for slot,atts in attachments.items():
        for an,att in atts.items():
            setup_vertices[(slot,an)]=att.get("vertices",[]) or []

    for fi,state in enumerate(frames):
        t=_frame_time(fi,fps)
        byidx={int(p["index"]):p for p in state["parts"]}
        order_rows=[]

        for slot,m in meta.items():
            idx=int(m["part_index"])
            p=byidx.get(idx)
            if not p:
                continue
            cell_key=_part_key_to_cell(p)
            aname=m["attachment_names"].get(cell_key)
            visible=_part_visible(p,regions,show_hidden=show_hidden) and aname is not None
            alpha=float(p.get("opacity",1.0) if isinstance(p.get("opacity",1.0),(int,float)) else 1.0) if visible else 0.0
            color=_rgba_hex(alpha)

            # Attachment/color timelines.
            old=prev_slot.get(slot,{
                "attachment":m["setup_attachment"],
                "color":next((s.get("color","ffffffff") for s in slots if s["name"]==slot),"ffffffff")
            })
            cur={"attachment":aname if aname is not None else old["attachment"],"color":color}
            if old["attachment"]!=cur["attachment"]:
                slot_tl.setdefault(slot,{}).setdefault("attachment",[]).append({"time":t,"name":cur["attachment"]})
            if old["color"]!=cur["color"]:
                k={"time":t,"color":cur["color"]}
                if stepped:k["curve"]="stepped"
                slot_tl.setdefault(slot,{}).setdefault("color",[]).append(k)
            prev_slot[slot]=cur

            # Deform only active attachment.
            if visible and aname is not None:
                region_name,cell,_=regions[cell_key]
                verts,uvs,tris=_part_world_geometry(p,cell,mesh_v_flip=mesh_v_flip)
                base=setup_vertices.get((slot,aname),[])
                if verts and len(verts)==len(base):
                    delta=[float(v)-float(b) for v,b in zip(verts,base)]
                    offset,trimmed=_trim_zero_deform(delta)
                    key={"time":t}
                    if trimmed is not None:
                        if offset:
                            key["offset"]=int(offset)
                        key["vertices"]=trimmed
                    if stepped:
                        key["curve"]="stepped"
                    deform_skin.setdefault(slot,{}).setdefault(aname,[]).append(key)
                    deform_keys+=1

            order_rows.append((int(p.get("priority",0) or 0),idx,slot))

        cur_order=[s for _,_,s in sorted(order_rows)]
        if fi>0 and cur_order and cur_order!=prev_order:
            offsets=[]
            for ci,slot in enumerate(cur_order):
                if slot in prev_order:
                    si=prev_order.index(slot)
                    off=ci-si
                    if off!=0:offsets.append({"slot":slot,"offset":off})
            if offsets:
                draworder.append({"time":t,"offsets":offsets})
            prev_order=cur_order

    anim={}
    if slot_tl:anim["slots"]=slot_tl
    if deform_skin:anim["deform"]={"default":deform_skin}
    if draworder:anim["draworder"]=draworder
    # Ensure importer always sees an animation even in degenerate cases.
    if not anim:
        anim={"bones":{"root":{"rotate":[{"time":0.0,"angle":0.0}]}}}

    doc={
        "skeleton":{
            "spine":"4.2.00",
            "images":"./textures/",
            "ss6Runtime":"ss6python_runtime_v22",
            "ss6Animation":anim_name,
            "ss6Frame":int(setup_frame),
            "ss6Mode":"baked-world-mesh-deform"
        },
        "bones":bones,
        "slots":slots,
        "skins":[{"name":"default","attachments":attachments}],
        "animations":{
            "setup":{"bones":{"root":{"rotate":[{"time":0.0,"angle":0.0}]}}},
            anim_name:anim
        }
    }

    json_path=out/f"{skeleton_name}.json"
    json_path.write_text(json.dumps(doc,ensure_ascii=False,indent=2),encoding="utf-8")

    timeline_count=0
    for slot,v in deform_skin.items():
        timeline_count+=len(v)
    slot_timeline_count=sum(len(v) for v in slot_tl.values())

    report={
        "json":str(json_path),
        "atlas":str(atlas_path),
        "animation":anim_name,
        "setup_frame":int(setup_frame),
        "frame_count":int(rt.frame_count),
        "fps":float(rt.fps),
        "export_mode":"baked-world-mesh-deform",
        "bones":len(bones),
        "slots":len(slots),
        "deform_timelines":timeline_count,
        "deform_keyframes":deform_keys,
        "slot_timelines":slot_timeline_count,
        "draworder_keyframes":len(draworder),
        "stepped":bool(stepped),
        "warnings":warnings,
    }
    (out/"spine_export_report.json").write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding="utf-8")
    return report

def bundle_to_spine_baked(bundle_path,output_dir,setup_frame=0,name=None,
                          animation_name=None,animation_index=None,data_animation=None,
                          root_path_id=None,mesh_v_flip=False,show_hidden=False,stepped=False):
    out=Path(output_dir)
    extracted=out/"_extracted"
    extract_bundle(
        bundle_path,extracted,
        animation_name=animation_name,
        animation_index=animation_index,
        data_animation=data_animation,
        root_path_id=root_path_id,
        all_animations=False
    )
    result=export_spine_baked(
        extracted/"parts_raw.json",
        extracted/"animation_raw.json",
        extracted/"cellmap.json",
        extracted/"textures",
        out,
        setup_frame=setup_frame,
        name=name or _safe(Path(bundle_path).stem),
        mesh_v_flip=mesh_v_flip,
        show_hidden=show_hidden,
        stepped=stepped
    )
    result["extract_manifest"]=str(extracted/"extract_manifest.json")
    return result


# ---------------------------------------------------------------------------
# v0.17 per-frame attachment baked exporter
# ---------------------------------------------------------------------------

def export_spine_frame_swap(parts_raw_path,animation_raw_path,cellmap_path,texture_dir,
                            output_dir,setup_frame=0,name=None,mesh_v_flip=False,
                            show_hidden=False,dedupe=True):
    """
    Maximum-compatibility animation exporter.

    No animated bones.
    No deform timelines.

    Each visible SS6 part gets one Spine slot on the root bone. For every frame,
    the evaluated final geometry is baked into a mesh attachment. The animation
    is reproduced by a stepped attachment timeline that switches to the correct
    baked mesh each frame.

    This is intentionally data-heavy but provides a very strong fidelity baseline.
    """
    out=Path(output_dir)
    out.mkdir(parents=True,exist_ok=True)

    rt=Runtime.from_files(parts_raw_path,animation_raw_path)
    frames=_eval_all_frames(rt)
    maps=_parse_maps(_load(cellmap_path))
    regions=_build_regions(maps)

    skeleton_name=_safe(name or Path(output_dir).name or "ss6_character")
    atlas_path=out/f"{skeleton_name}.atlas"
    _write_atlas(maps,texture_dir,out,atlas_path)

    fps=float(max(rt.fps,1.0))
    anim_name=str(frames[0].get("animation") or "animation")

    # All parts that ever reference a known cell.
    visual_indices=[]
    part_names={}
    for state in frames:
        for p in state["parts"]:
            idx=int(p["index"])
            key=_part_key_to_cell(p)
            if key is None or key not in regions:
                continue
            if idx not in visual_indices:
                visual_indices.append(idx)
            part_names[idx]=str(p["name"])

    # Use setup frame priority for base slot order.
    sf=frames[int(setup_frame)]
    sf_byidx={int(p["index"]):p for p in sf["parts"]}
    visual_indices.sort(key=lambda idx:(
        int(sf_byidx.get(idx,{}).get("priority",0) or 0),
        idx
    ))

    bones=[{"name":"root"}]
    slots=[]
    skin_attachments={}
    slot_timelines={}
    geometry_cache={}
    frame_attachment_name={}
    warnings=[]
    total_attachments=0

    def geom_signature(cell_key,verts,uvs,tris):
        if not dedupe:
            return None
        # Rounded signature so identical sampled geometry can reuse attachment.
        return (
            tuple(cell_key),
            tuple(round(float(x),5) for x in verts),
            tuple(round(float(x),6) for x in uvs),
            tuple(int(x) for x in tris)
        )

    # First create all frame-specific geometry attachments.
    for idx in visual_indices:
        slot_name=part_names[idx]
        skin_attachments[slot_name]={}
        cache_for_slot={}
        previous_attachment=None

        for fi,state in enumerate(frames):
            byidx={int(p["index"]):p for p in state["parts"]}
            p=byidx.get(idx)
            if p is None:
                frame_attachment_name[(idx,fi)]=None
                continue

            cell_key=_part_key_to_cell(p)
            visible=_part_visible(p,regions,show_hidden=show_hidden)
            if cell_key is None or cell_key not in regions or not visible:
                frame_attachment_name[(idx,fi)]=None
                continue

            region_name,cell,_=regions[cell_key]
            verts,uvs,tris=_part_world_geometry(p,cell,mesh_v_flip=mesh_v_flip)
            if not verts:
                frame_attachment_name[(idx,fi)]=None
                warnings.append(f"{slot_name}: frame {fi} geometry missing")
                continue

            sig=geom_signature(cell_key,verts,uvs,tris)
            if sig is not None and sig in cache_for_slot:
                aname=cache_for_slot[sig]
            else:
                aname=f"{slot_name}__f{fi:03d}"
                # Ensure uniqueness if same name somehow already used.
                suffix=1
                base=aname
                while aname in skin_attachments[slot_name]:
                    aname=f"{base}_{suffix}"
                    suffix+=1

                skin_attachments[slot_name][aname]={
                    "type":"mesh",
                    "path":region_name,
                    "uvs":uvs,
                    "triangles":tris,
                    "vertices":verts,
                    "hull":len(verts)//2,
                    "width":float(cell.get("width",0)),
                    "height":float(cell.get("height",0)),
                }
                total_attachments+=1
                if sig is not None:
                    cache_for_slot[sig]=aname

            frame_attachment_name[(idx,fi)]=aname

        # Setup attachment: selected frame if visible, otherwise first visible frame.
        setup_attachment=frame_attachment_name.get((idx,int(setup_frame)))
        if setup_attachment is None:
            for fi in range(len(frames)):
                q=frame_attachment_name.get((idx,fi))
                if q is not None:
                    setup_attachment=q
                    break

        slot={"name":slot_name,"bone":"root"}
        if setup_attachment is not None:
            slot["attachment"]=setup_attachment

        p0=sf_byidx.get(idx)
        visible0=False
        alpha0=1.0
        if p0 is not None:
            visible0=_part_visible(p0,regions,show_hidden=show_hidden)
            alpha0=float(p0.get("opacity",1.0) if isinstance(p0.get("opacity",1.0),(int,float)) else 1.0)
        if not visible0:
            alpha0=0.0
        if alpha0<0.9999:
            slot["color"]=_rgba_hex(alpha0)
        slots.append(slot)

        # Build stepped attachment timeline. Include frame 0 explicitly so the
        # animation is self-contained even if setup_frame != 0.
        keys=[]
        prev_marker=object()
        prev=None
        for fi in range(len(frames)):
            aname=frame_attachment_name.get((idx,fi))
            # None means hide attachment.
            if fi==0 or aname!=prev:
                key={"time":_frame_time(fi,fps),"curve":"stepped"}
                if aname is not None:
                    key["name"]=aname
                keys.append(key)
                prev=aname
        if keys:
            slot_timelines.setdefault(slot_name,{})["attachment"]=keys

        # Opacity / hidden timeline.
        color_keys=[]
        prev_color=None
        for fi,state in enumerate(frames):
            byidx={int(p["index"]):p for p in state["parts"]}
            p=byidx.get(idx)
            if p is None:
                color="ffffff00"
            else:
                visible=_part_visible(p,regions,show_hidden=show_hidden)
                alpha=float(p.get("opacity",1.0) if isinstance(p.get("opacity",1.0),(int,float)) else 1.0) if visible else 0.0
                color=_rgba_hex(alpha)
            if fi==0 or color!=prev_color:
                color_keys.append({
                    "time":_frame_time(fi,fps),
                    "color":color,
                    "curve":"stepped"
                })
                prev_color=color
        # Avoid redundant constant-opaque timeline.
        if not (len(color_keys)==1 and color_keys[0]["color"]=="ffffffff"):
            slot_timelines.setdefault(slot_name,{})["color"]=color_keys

    # Draw order sampled per frame.
    setup_order=[s["name"] for s in slots]
    draworder=[]
    prev_order=setup_order
    for fi,state in enumerate(frames):
        rows=[]
        for p in state["parts"]:
            idx=int(p["index"])
            if idx not in visual_indices:
                continue
            rows.append((int(p.get("priority",0) or 0),idx,part_names[idx]))
        cur=[s for _,_,s in sorted(rows)]
        if fi>0 and cur and cur!=prev_order:
            offsets=[]
            # Spine offsets are against setup slot order.
            for ci,slot_name in enumerate(cur):
                if slot_name not in setup_order:
                    continue
                si=setup_order.index(slot_name)
                off=ci-si
                if off!=0:
                    offsets.append({"slot":slot_name,"offset":off})
            if offsets:
                draworder.append({
                    "time":_frame_time(fi,fps),
                    "offsets":offsets
                })
            prev_order=cur

    animation={"slots":slot_timelines}
    if draworder:
        animation["draworder"]=draworder

    doc={
        "skeleton":{
            "spine":"4.2.00",
            "images":"./textures/",
            "ss6Runtime":"ss6python_runtime_v22",
            "ss6Animation":anim_name,
            "ss6Frame":int(setup_frame),
            "ss6Mode":"frame-swap-baked-mesh"
        },
        "bones":bones,
        "slots":slots,
        "skins":[{"name":"default","attachments":skin_attachments}],
        "animations":{
            "setup":{"bones":{"root":{"rotate":[{"time":0.0,"angle":0.0}]}}},
            anim_name:animation
        }
    }

    json_path=out/f"{skeleton_name}.json"
    json_path.write_text(json.dumps(doc,ensure_ascii=False,indent=2),encoding="utf-8")

    attachment_timeline_count=sum(
        1 for v in slot_timelines.values() if "attachment" in v
    )
    attachment_keyframes=sum(
        len(v.get("attachment",[])) for v in slot_timelines.values()
    )
    color_timeline_count=sum(
        1 for v in slot_timelines.values() if "color" in v
    )
    color_keyframes=sum(
        len(v.get("color",[])) for v in slot_timelines.values()
    )

    report={
        "json":str(json_path),
        "atlas":str(atlas_path),
        "animation":anim_name,
        "frame_count":int(rt.frame_count),
        "fps":float(rt.fps),
        "export_mode":"frame-swap-baked-mesh",
        "bones":1,
        "slots":len(slots),
        "mesh_attachments":total_attachments,
        "attachment_timelines":attachment_timeline_count,
        "attachment_keyframes":attachment_keyframes,
        "color_timelines":color_timeline_count,
        "color_keyframes":color_keyframes,
        "draworder_keyframes":len(draworder),
        "deform_timelines":0,
        "dedupe":bool(dedupe),
        "warnings":warnings,
    }
    (out/"spine_export_report.json").write_text(
        json.dumps(report,ensure_ascii=False,indent=2),
        encoding="utf-8"
    )
    return report

def bundle_to_spine_frame_swap(bundle_path,output_dir,setup_frame=0,name=None,
                               animation_name=None,animation_index=None,data_animation=None,
                               root_path_id=None,mesh_v_flip=False,show_hidden=False,
                               dedupe=True):
    out=Path(output_dir)
    extracted=out/"_extracted"
    extract_bundle(
        bundle_path,extracted,
        animation_name=animation_name,
        animation_index=animation_index,
        data_animation=data_animation,
        root_path_id=root_path_id,
        all_animations=False
    )
    result=export_spine_frame_swap(
        extracted/"parts_raw.json",
        extracted/"animation_raw.json",
        extracted/"cellmap.json",
        extracted/"textures",
        out,
        setup_frame=setup_frame,
        name=name or _safe(Path(bundle_path).stem),
        mesh_v_flip=mesh_v_flip,
        show_hidden=show_hidden,
        dedupe=dedupe
    )
    result["extract_manifest"]=str(extracted/"extract_manifest.json")
    return result


# ---------------------------------------------------------------------------
# v0.18 all-animation frame-swap exporter
# ---------------------------------------------------------------------------

def _load_runtime_set(parts_raw_path, animation_entries):
    """
    animation_entries: list of {"name","animation_raw",...}
    Returns [(entry, Runtime, frames), ...]
    """
    out=[]
    for e in animation_entries:
        rt=Runtime.from_files(parts_raw_path,e["animation_raw"])
        frames=_eval_all_frames(rt)
        out.append((e,rt,frames))
    return out

def _select_setup_animation(runtime_set, setup_animation_name=None):
    if setup_animation_name:
        for i,(e,rt,frames) in enumerate(runtime_set):
            if str(e["name"])==str(setup_animation_name):
                return i
        raise RuntimeError(
            f"Setup animation not found: {setup_animation_name}. "
            f"Available: {[x[0]['name'] for x in runtime_set]}"
        )

    # Prefer a stable idle/stand animation when available.
    preferred=("mot_stand","stand","idle","mot_ready","ready","mot_action_01")
    for target in preferred:
        for i,(e,rt,frames) in enumerate(runtime_set):
            if str(e["name"]).lower()==target:
                return i
    return 0

def _filter_animation_entries(entries, include=None, exclude=None):
    inc=re.compile(include,re.I) if include else None
    exc=re.compile(exclude,re.I) if exclude else None
    out=[]
    for e in entries:
        name=str(e["name"])
        if inc and not inc.search(name):
            continue
        if exc and exc.search(name):
            continue
        out.append(e)
    return out

def export_spine_frame_swap_all(parts_raw_path, animation_entries, cellmap_path, texture_dir,
                                output_dir, setup_animation_name=None, setup_frame=0,
                                name=None, mesh_v_flip=False, show_hidden=False,
                                dedupe=True):
    """
    Export multiple SS6 animations into ONE Spine 4.2 JSON using the v0.17
    per-frame baked attachment switching strategy.

    All animations share:
      - one root bone
      - one slot set
      - one atlas / texture set
      - one skin containing all baked frame attachments

    Attachment names are animation-qualified to avoid collisions.
    """
    out=Path(output_dir)
    out.mkdir(parents=True,exist_ok=True)

    maps=_parse_maps(_load(cellmap_path))
    regions=_build_regions(maps)

    runtime_set=_load_runtime_set(parts_raw_path,animation_entries)
    if not runtime_set:
        raise RuntimeError("No animations selected for export.")

    setup_idx=_select_setup_animation(runtime_set,setup_animation_name)
    setup_entry,setup_rt,setup_frames=runtime_set[setup_idx]
    if setup_frame<0 or setup_frame>=len(setup_frames):
        raise RuntimeError(
            f"setup_frame {setup_frame} out of range for {setup_entry['name']} "
            f"(frames={len(setup_frames)})"
        )

    skeleton_name=_safe(name or Path(output_dir).name or "ss6_character")
    atlas_path=out/f"{skeleton_name}.atlas"
    _write_atlas(maps,texture_dir,out,atlas_path)

    # Union of every part that is drawable in any selected animation.
    visual_indices=[]
    part_names={}
    used_cell_any={}
    for e,rt,frames in runtime_set:
        for state in frames:
            for p in state["parts"]:
                idx=int(p["index"])
                key=_part_key_to_cell(p)
                if key is None or key not in regions:
                    continue
                part_names[idx]=str(p["name"])
                if idx not in visual_indices:
                    visual_indices.append(idx)
                used_cell_any.setdefault(idx,[])
                if key not in used_cell_any[idx]:
                    used_cell_any[idx].append(key)

    setup_state=setup_frames[int(setup_frame)]
    setup_byidx={int(p["index"]):p for p in setup_state["parts"]}

    # Stable base slot order from setup pose, then index fallback.
    visual_indices.sort(key=lambda idx:(
        int(setup_byidx.get(idx,{}).get("priority",0) or 0),
        idx
    ))

    bones=[{"name":"root"}]
    slots=[]
    skin_attachments={}
    warnings=[]

    # Global geometry cache PER SLOT. This enables dedupe across animations too.
    global_geom_cache={idx:{} for idx in visual_indices}
    frame_attachment={}  # (anim_name, part_idx, frame) -> attachment name
    total_attachments=0

    def geom_signature(cell_key,verts,uvs,tris):
        if not dedupe:
            return None
        return (
            tuple(cell_key),
            tuple(round(float(x),5) for x in verts),
            tuple(round(float(x),6) for x in uvs),
            tuple(int(x) for x in tris)
        )

    # First pass: create every baked attachment needed by every animation.
    for idx in visual_indices:
        slot_name=part_names[idx]
        skin_attachments[slot_name]={}

    for e,rt,frames in runtime_set:
        anim_name=str(e["name"])
        anim_safe=_safe(anim_name)
        for fi,state in enumerate(frames):
            byidx={int(p["index"]):p for p in state["parts"]}
            for idx in visual_indices:
                p=byidx.get(idx)
                if p is None:
                    frame_attachment[(anim_name,idx,fi)]=None
                    continue

                cell_key=_part_key_to_cell(p)
                visible=_part_visible(p,regions,show_hidden=show_hidden)
                if cell_key is None or cell_key not in regions or not visible:
                    frame_attachment[(anim_name,idx,fi)]=None
                    continue

                region_name,cell,_=regions[cell_key]
                verts,uvs,tris=_part_world_geometry(p,cell,mesh_v_flip=mesh_v_flip)
                if not verts:
                    warnings.append(f"{anim_name}/{part_names[idx]}: frame {fi} geometry missing")
                    frame_attachment[(anim_name,idx,fi)]=None
                    continue

                sig=geom_signature(cell_key,verts,uvs,tris)
                cache=global_geom_cache[idx]
                if sig is not None and sig in cache:
                    aname=cache[sig]
                else:
                    slot_name=part_names[idx]
                    aname=f"{slot_name}__{anim_safe}__f{fi:03d}"
                    base=aname
                    suffix=1
                    while aname in skin_attachments[slot_name]:
                        aname=f"{base}_{suffix}"
                        suffix+=1

                    skin_attachments[slot_name][aname]={
                        "type":"mesh",
                        "path":region_name,
                        "uvs":uvs,
                        "triangles":tris,
                        "vertices":verts,
                        "hull":len(verts)//2,
                        "width":float(cell.get("width",0)),
                        "height":float(cell.get("height",0)),
                    }
                    total_attachments+=1
                    if sig is not None:
                        cache[sig]=aname

                frame_attachment[(anim_name,idx,fi)]=aname

    # Setup slots.
    setup_anim_name=str(setup_entry["name"])
    for idx in visual_indices:
        slot_name=part_names[idx]
        setup_attachment=frame_attachment.get((setup_anim_name,idx,int(setup_frame)))

        # If hidden in setup pose, find first valid attachment anywhere so the
        # slot remains structurally importable, then make it transparent.
        if setup_attachment is None:
            for e,rt,frames in runtime_set:
                an=str(e["name"])
                found=None
                for fi in range(len(frames)):
                    q=frame_attachment.get((an,idx,fi))
                    if q is not None:
                        found=q
                        break
                if found is not None:
                    setup_attachment=found
                    break

        s={"name":slot_name,"bone":"root"}
        if setup_attachment is not None:
            s["attachment"]=setup_attachment

        p0=setup_byidx.get(idx)
        visible0=False
        alpha0=1.0
        if p0 is not None:
            visible0=_part_visible(p0,regions,show_hidden=show_hidden)
            alpha0=float(
                p0.get("opacity",1.0)
                if isinstance(p0.get("opacity",1.0),(int,float))
                else 1.0
            )
        if not visible0:
            alpha0=0.0
        if alpha0<0.9999:
            s["color"]=_rgba_hex(alpha0)
        slots.append(s)

    setup_order=[s["name"] for s in slots]

    # Second pass: build every Spine animation.
    animations={}
    animation_reports=[]

    # Keep setup placeholder as before.
    animations["setup"]={"bones":{"root":{"rotate":[{"time":0.0,"angle":0.0}]}}}

    for e,rt,frames in runtime_set:
        anim_name=str(e["name"])
        fps=float(max(rt.fps,1.0))
        slot_timelines={}
        draworder=[]

        # Attachment and opacity timelines.
        for idx in visual_indices:
            slot_name=part_names[idx]
            attachment_keys=[]
            color_keys=[]
            prev_att=object()
            prev_color=None

            for fi,state in enumerate(frames):
                t=_frame_time(fi,fps)
                byidx={int(p["index"]):p for p in state["parts"]}
                p=byidx.get(idx)

                aname=frame_attachment.get((anim_name,idx,fi))

                if fi==0 or aname!=prev_att:
                    k={"time":t,"curve":"stepped"}
                    if aname is not None:
                        k["name"]=aname
                    attachment_keys.append(k)
                    prev_att=aname

                if p is None:
                    color="ffffff00"
                else:
                    visible=_part_visible(p,regions,show_hidden=show_hidden)
                    alpha=float(
                        p.get("opacity",1.0)
                        if isinstance(p.get("opacity",1.0),(int,float))
                        else 1.0
                    ) if visible else 0.0
                    color=_rgba_hex(alpha)

                if fi==0 or color!=prev_color:
                    color_keys.append({
                        "time":t,
                        "color":color,
                        "curve":"stepped"
                    })
                    prev_color=color

            if attachment_keys:
                slot_timelines.setdefault(slot_name,{})["attachment"]=attachment_keys

            # Omit constant fully opaque color timeline.
            if not (len(color_keys)==1 and color_keys[0]["color"]=="ffffffff"):
                slot_timelines.setdefault(slot_name,{})["color"]=color_keys

        # Draw order sampled against the global setup order.
        prev_order=setup_order
        for fi,state in enumerate(frames):
            rows=[]
            for p in state["parts"]:
                idx=int(p["index"])
                if idx not in visual_indices:
                    continue
                rows.append((int(p.get("priority",0) or 0),idx,part_names[idx]))
            cur=[s for _,_,s in sorted(rows)]
            if fi>0 and cur and cur!=prev_order:
                offsets=[]
                for ci,slot_name in enumerate(cur):
                    if slot_name not in setup_order:
                        continue
                    si=setup_order.index(slot_name)
                    off=ci-si
                    if off!=0:
                        offsets.append({"slot":slot_name,"offset":off})
                if offsets:
                    draworder.append({
                        "time":_frame_time(fi,fps),
                        "offsets":offsets
                    })
                prev_order=cur

        # v0.20: explicitly extend this animation through the END of the
        # final sampled SS6 frame. The all-animation exporter missed this
        # fix in v0.19.
        end_time=_end_time(len(frames),fps)
        anim={
            "bones":{
                "root":{
                    "rotate":[
                        {"time":0.0,"angle":0.0},
                        {"time":end_time,"angle":0.0}
                    ]
                }
            },
            "slots":slot_timelines
        }
        if draworder:
            anim["draworder"]=draworder
        animations[anim_name]=anim

        attachment_timeline_count=sum(
            1 for v in slot_timelines.values() if "attachment" in v
        )
        attachment_keyframes=sum(
            len(v.get("attachment",[])) for v in slot_timelines.values()
        )
        color_timeline_count=sum(
            1 for v in slot_timelines.values() if "color" in v
        )
        color_keyframes=sum(
            len(v.get("color",[])) for v in slot_timelines.values()
        )

        animation_reports.append({
            "name":anim_name,
            "frame_count":int(rt.frame_count),
            "fps":float(rt.fps),
            "duration":_end_time(int(rt.frame_count),rt.fps),
            "terminal_hold":True,
            "attachment_timelines":attachment_timeline_count,
            "attachment_keyframes":attachment_keyframes,
            "color_timelines":color_timeline_count,
            "color_keyframes":color_keyframes,
            "draworder_keyframes":len(draworder),
        })

    doc={
        "skeleton":{
            "spine":"4.2.00",
            "images":"./textures/",
            "ss6Runtime":"ss6python_runtime_v22",
            "ss6Mode":"frame-swap-all-animations",
            "ss6SetupAnimation":setup_anim_name,
            "ss6SetupFrame":int(setup_frame)
        },
        "bones":bones,
        "slots":slots,
        "skins":[{"name":"default","attachments":skin_attachments}],
        "animations":animations
    }

    json_path=out/f"{skeleton_name}.json"
    json_path.write_text(
        json.dumps(doc,ensure_ascii=False,indent=2),
        encoding="utf-8"
    )

    report={
        "json":str(json_path),
        "atlas":str(atlas_path),
        "export_mode":"frame-swap-all-animations",
        "setup_animation":setup_anim_name,
        "setup_frame":int(setup_frame),
        "animations_exported":len(runtime_set),
        "animation_names":[str(e["name"]) for e,_,_ in runtime_set],
        "bones":1,
        "slots":len(slots),
        "mesh_attachments":total_attachments,
        "dedupe":bool(dedupe),
        "animations":animation_reports,
        "warnings":warnings,
    }
    (out/"spine_export_report.json").write_text(
        json.dumps(report,ensure_ascii=False,indent=2),
        encoding="utf-8"
    )
    return report

def bundle_to_spine_frame_swap_all(bundle_path,output_dir,setup_animation_name=None,
                                   setup_frame=0,name=None,include=None,exclude=None,
                                   data_animation=None,root_path_id=None,
                                   mesh_v_flip=False,show_hidden=False,dedupe=True):
    """
    One command:
      bundle -> extract all animations -> one combined Spine JSON
    """
    out=Path(output_dir)
    extracted=out/"_extracted"

    manifest=extract_bundle(
        bundle_path,extracted,
        data_animation=data_animation,
        root_path_id=root_path_id,
        all_animations=True
    )

    entries=[]
    for item in manifest.get("all_animation_outputs",[]):
        entries.append({
            "index":item["index"],
            "name":item["name"],
            "animation_raw":str(extracted/item["animation_raw"])
        })

    entries=_filter_animation_entries(entries,include=include,exclude=exclude)
    if not entries:
        raise RuntimeError(
            f"No animations matched include={include!r}, exclude={exclude!r}"
        )

    # If explicit setup animation was filtered out, keep error actionable.
    if setup_animation_name and setup_animation_name not in [e["name"] for e in entries]:
        raise RuntimeError(
            f"Setup animation {setup_animation_name!r} was not selected. "
            f"Selected animations: {[e['name'] for e in entries]}"
        )

    result=export_spine_frame_swap_all(
        extracted/"parts_raw.json",
        entries,
        extracted/"cellmap.json",
        extracted/"textures",
        out,
        setup_animation_name=setup_animation_name,
        setup_frame=setup_frame,
        name=name or _safe(Path(bundle_path).stem),
        mesh_v_flip=mesh_v_flip,
        show_hidden=show_hidden,
        dedupe=dedupe
    )
    result["extract_manifest"]=str(extracted/"extract_manifest.json")
    return result


# ---------------------------------------------------------------------------
# v0.24 optimized all-animation frame-swap exporter
# ---------------------------------------------------------------------------

def _quantize_float(v, tol):
    if tol is None or tol <= 0:
        return round(float(v), 9)
    return int(round(float(v) / float(tol)))

def _optimized_geom_signature(cell_key, verts, uvs, tris, tolerance=1e-4):
    """
    Approximate geometry signature.

    - region/cell must match exactly
    - triangle topology must match exactly
    - UVs are quantized tightly
    - vertex coordinates are quantized using user tolerance

    tolerance=0 means effectively exact (9 decimal places).
    """
    return (
        tuple(cell_key),
        tuple(_quantize_float(x, tolerance) for x in verts),
        tuple(_quantize_float(x, 1e-7) for x in uvs),
        tuple(int(x) for x in tris),
    )

def _sample_indices(frame_count, source_fps, export_fps=None, frame_step=None):
    """
    Select source sample indices while preserving original animation time.

    frame_step takes precedence over export_fps.
    The final source frame is included if not already selected.
    """
    n=int(frame_count)
    if n<=0:
        return []

    if frame_step is not None:
        step=max(1,int(frame_step))
        idx=list(range(0,n,step))
    elif export_fps is not None and float(export_fps)>0 and float(export_fps)<float(source_fps)-1e-9:
        target=float(export_fps)
        duration=(n-1)/float(source_fps)
        # Sample target-clock times and map to nearest source frame.
        count=int(math.floor(duration*target+1e-9))+1
        idx=[]
        for k in range(count):
            t=k/target
            fi=int(round(t*float(source_fps)))
            fi=max(0,min(n-1,fi))
            if not idx or idx[-1]!=fi:
                idx.append(fi)
    else:
        idx=list(range(n))

    if idx[-1] != n-1:
        idx.append(n-1)
    return idx

def _visible_order_signature(state, visual_indices, part_names, regions, show_hidden=False):
    rows=[]
    allowed=set(int(x) for x in visual_indices)
    for p in state["parts"]:
        idx=int(p["index"])
        if idx not in allowed:
            continue
        if not _part_visible(p,regions,show_hidden=show_hidden):
            continue
        rows.append((int(p.get("priority",0) or 0),idx,part_names[idx]))
    return tuple(s for _,_,s in sorted(rows))

def _full_order(state, visual_indices, part_names):
    allowed=set(int(x) for x in visual_indices)
    rows=[]
    for p in state["parts"]:
        idx=int(p["index"])
        if idx not in allowed:
            continue
        rows.append((int(p.get("priority",0) or 0),idx,part_names[idx]))
    return [s for _,_,s in sorted(rows)]

def export_spine_frame_swap_all(parts_raw_path, animation_entries, cellmap_path, texture_dir,
                                output_dir, setup_animation_name=None, setup_frame=0,
                                name=None, mesh_v_flip=False, show_hidden=False,
                                dedupe=True, dedupe_tolerance=1e-4,
                                export_fps=None, frame_step=None):
    """
    v0.24 optimized combined frame-swap exporter.

    Fidelity model is unchanged from v0.22:
      - one root bone
      - baked mesh attachment per sampled visual state
      - stepped attachment switching

    Optimizations:
      - approximate cross-frame/cross-animation dedupe
      - sparse opacity timelines
      - draw-order changes only when visible ordering changes
      - optional downsampling
    """
    out=Path(output_dir)
    out.mkdir(parents=True,exist_ok=True)

    maps=_parse_maps(_load(cellmap_path))
    regions=_build_regions(maps)

    runtime_set=_load_runtime_set(parts_raw_path,animation_entries)
    if not runtime_set:
        raise RuntimeError("No animations selected for export.")

    setup_idx=_select_setup_animation(runtime_set,setup_animation_name)
    setup_entry,setup_rt,setup_frames=runtime_set[setup_idx]
    if setup_frame<0 or setup_frame>=len(setup_frames):
        raise RuntimeError(
            f"setup_frame {setup_frame} out of range for {setup_entry['name']} "
            f"(frames={len(setup_frames)})"
        )

    skeleton_name=_safe(name or Path(output_dir).name or "ss6_character")
    atlas_path=out/f"{skeleton_name}.atlas"
    _write_atlas(maps,texture_dir,out,atlas_path)

    # Union of visual parts over all original frames.
    visual_indices=[]
    part_names={}
    for e,rt,frames in runtime_set:
        for state in frames:
            for p in state["parts"]:
                idx=int(p["index"])
                key=_part_key_to_cell(p)
                if key is None or key not in regions:
                    continue
                part_names[idx]=str(p["name"])
                if idx not in visual_indices:
                    visual_indices.append(idx)

    setup_state=setup_frames[int(setup_frame)]
    setup_byidx={int(p["index"]):p for p in setup_state["parts"]}
    visual_indices.sort(key=lambda idx:(
        int(setup_byidx.get(idx,{}).get("priority",0) or 0),
        idx
    ))

    bones=[{"name":"root"}]
    slots=[]
    skin_attachments={part_names[idx]:{} for idx in visual_indices}
    warnings=[]

    # One cache per slot, shared across ALL animations.
    global_geom_cache={idx:{} for idx in visual_indices}
    frame_attachment={}  # (anim_name, part_idx, source_frame) -> attachment name
    total_attachments=0
    dedupe_hits=0

    # Per-animation sample plans.
    sample_plan={}
    for e,rt,frames in runtime_set:
        sample_plan[str(e["name"])]=_sample_indices(
            len(frames),rt.fps,export_fps=export_fps,frame_step=frame_step
        )

    # Build baked attachments only for selected sample frames.
    for e,rt,frames in runtime_set:
        anim_name=str(e["name"])
        anim_safe=_safe(anim_name)
        for source_fi in sample_plan[anim_name]:
            state=frames[source_fi]
            byidx={int(p["index"]):p for p in state["parts"]}

            for idx in visual_indices:
                p=byidx.get(idx)
                if p is None:
                    frame_attachment[(anim_name,idx,source_fi)]=None
                    continue

                cell_key=_part_key_to_cell(p)
                visible=_part_visible(p,regions,show_hidden=show_hidden)
                if cell_key is None or cell_key not in regions or not visible:
                    frame_attachment[(anim_name,idx,source_fi)]=None
                    continue

                region_name,cell,_=regions[cell_key]
                verts,uvs,tris=_part_world_geometry(p,cell,mesh_v_flip=mesh_v_flip)
                if not verts:
                    warnings.append(f"{anim_name}/{part_names[idx]}: frame {source_fi} geometry missing")
                    frame_attachment[(anim_name,idx,source_fi)]=None
                    continue

                sig=None
                if dedupe:
                    sig=_optimized_geom_signature(
                        cell_key,verts,uvs,tris,tolerance=dedupe_tolerance
                    )

                cache=global_geom_cache[idx]
                if sig is not None and sig in cache:
                    aname=cache[sig]
                    dedupe_hits+=1
                else:
                    slot_name=part_names[idx]
                    aname=f"{slot_name}__{anim_safe}__f{source_fi:03d}"
                    base=aname
                    suffix=1
                    while aname in skin_attachments[slot_name]:
                        aname=f"{base}_{suffix}"
                        suffix+=1

                    skin_attachments[slot_name][aname]={
                        "type":"mesh",
                        "path":region_name,
                        "uvs":uvs,
                        "triangles":tris,
                        "vertices":verts,
                        "hull":len(verts)//2,
                        "width":float(cell.get("width",0)),
                        "height":float(cell.get("height",0)),
                    }
                    total_attachments+=1
                    if sig is not None:
                        cache[sig]=aname

                frame_attachment[(anim_name,idx,source_fi)]=aname

    # Setup slots from chosen setup animation/frame.
    setup_anim_name=str(setup_entry["name"])
    for idx in visual_indices:
        slot_name=part_names[idx]

        setup_attachment=frame_attachment.get((setup_anim_name,idx,int(setup_frame)))
        if setup_attachment is None:
            # Find any exported attachment so the slot is structurally valid.
            found=None
            for e,rt,frames in runtime_set:
                an=str(e["name"])
                for fi in sample_plan[an]:
                    q=frame_attachment.get((an,idx,fi))
                    if q is not None:
                        found=q;break
                if found is not None:
                    break
            setup_attachment=found

        s={"name":slot_name,"bone":"root"}
        if setup_attachment is not None:
            s["attachment"]=setup_attachment

        p0=setup_byidx.get(idx)
        visible0=False
        alpha0=1.0
        if p0 is not None:
            visible0=_part_visible(p0,regions,show_hidden=show_hidden)
            alpha0=float(
                p0.get("opacity",1.0)
                if isinstance(p0.get("opacity",1.0),(int,float))
                else 1.0
            )
        if not visible0:
            alpha0=0.0
        if alpha0<0.9999:
            s["color"]=_rgba_hex(alpha0)
        slots.append(s)

    setup_order=[s["name"] for s in slots]

    animations={
        "setup":{"bones":{"root":{"rotate":[{"time":0.0,"angle":0.0}]}}}
    }
    animation_reports=[]

    for e,rt,frames in runtime_set:
        anim_name=str(e["name"])
        fps=float(max(rt.fps,1.0))
        indices=sample_plan[anim_name]
        slot_timelines={}
        draworder=[]

        # Attachment timelines.
        for idx in visual_indices:
            slot_name=part_names[idx]
            attachment_keys=[]
            prev_att=object()

            for source_fi in indices:
                t=_frame_time(source_fi,fps)
                aname=frame_attachment.get((anim_name,idx,source_fi))
                if aname!=prev_att:
                    k={"time":t,"curve":"stepped"}
                    if aname is not None:
                        k["name"]=aname
                    attachment_keys.append(k)
                    prev_att=aname

            if attachment_keys:
                slot_timelines.setdefault(slot_name,{})["attachment"]=attachment_keys

        # Sparse opacity timelines:
        # Hidden frames are handled by attachment=null, so do NOT emit color=0
        # just because a part is hidden. Only real visible opacity changes matter.
        for idx in visual_indices:
            slot_name=part_names[idx]
            color_keys=[]
            prev_alpha=None
            any_nonopaque=False

            for source_fi in indices:
                state=frames[source_fi]
                byidx={int(p["index"]):p for p in state["parts"]}
                p=byidx.get(idx)
                if p is None:
                    continue
                visible=_part_visible(p,regions,show_hidden=show_hidden)
                if not visible:
                    continue

                alpha=float(
                    p.get("opacity",1.0)
                    if isinstance(p.get("opacity",1.0),(int,float))
                    else 1.0
                )
                if abs(alpha-1.0)>1e-6:
                    any_nonopaque=True

                if prev_alpha is None or abs(alpha-prev_alpha)>1e-6:
                    color_keys.append({
                        "time":_frame_time(source_fi,fps),
                        "color":_rgba_hex(alpha),
                        "curve":"stepped"
                    })
                    prev_alpha=alpha

            # Entirely opaque visible samples => no color timeline at all.
            if any_nonopaque and color_keys:
                slot_timelines.setdefault(slot_name,{})["color"]=color_keys

        # Draw order:
        # ignore changes caused only by hidden slots.
        prev_visible_sig=None
        prev_full_order=setup_order
        for source_fi in indices:
            state=frames[source_fi]
            visible_sig=_visible_order_signature(
                state,visual_indices,part_names,regions,show_hidden=show_hidden
            )
            full_order=_full_order(state,visual_indices,part_names)

            if prev_visible_sig is None:
                prev_visible_sig=visible_sig
                prev_full_order=full_order
                continue

            if visible_sig != prev_visible_sig:
                offsets=[]
                for ci,slot_name in enumerate(full_order):
                    if slot_name not in setup_order:
                        continue
                    si=setup_order.index(slot_name)
                    off=ci-si
                    if off!=0:
                        offsets.append({"slot":slot_name,"offset":off})
                if offsets:
                    draworder.append({
                        "time":_frame_time(source_fi,fps),
                        "offsets":offsets
                    })
                prev_visible_sig=visible_sig
                prev_full_order=full_order

        end_time=_end_time(len(frames),fps)
        anim={
            "bones":{
                "root":{
                    "rotate":[
                        {"time":0.0,"angle":0.0},
                        {"time":end_time,"angle":0.0}
                    ]
                }
            },
            "slots":slot_timelines
        }
        if draworder:
            anim["draworder"]=draworder
        animations[anim_name]=anim

        attachment_timeline_count=sum(
            1 for v in slot_timelines.values() if "attachment" in v
        )
        attachment_keyframes=sum(
            len(v.get("attachment",[])) for v in slot_timelines.values()
        )
        color_timeline_count=sum(
            1 for v in slot_timelines.values() if "color" in v
        )
        color_keyframes=sum(
            len(v.get("color",[])) for v in slot_timelines.values()
        )

        effective_fps = (
            float(export_fps)
            if export_fps is not None and float(export_fps)>0 and float(export_fps)<fps
            else (fps/max(1,int(frame_step)) if frame_step else fps)
        )

        animation_reports.append({
            "name":anim_name,
            "source_frame_count":int(rt.frame_count),
            "source_fps":float(rt.fps),
            "exported_samples":len(indices),
            "effective_export_fps":round(effective_fps,6),
            "sample_indices":indices,
            "duration":_end_time(int(rt.frame_count),rt.fps),
            "terminal_hold":True,
            "attachment_timelines":attachment_timeline_count,
            "attachment_keyframes":attachment_keyframes,
            "color_timelines":color_timeline_count,
            "color_keyframes":color_keyframes,
            "draworder_keyframes":len(draworder),
        })

    doc={
        "skeleton":{
            "spine":"4.2.00",
            "images":"./textures/",
            "ss6Runtime":"ss6python_runtime_v24",
            "ss6Mode":"frame-swap-all-animations-optimized",
            "ss6SetupAnimation":setup_anim_name,
            "ss6SetupFrame":int(setup_frame)
        },
        "bones":bones,
        "slots":slots,
        "skins":[{"name":"default","attachments":skin_attachments}],
        "animations":animations
    }

    json_path=out/f"{skeleton_name}.json"
    json_path.write_text(json.dumps(doc,ensure_ascii=False,separators=(",",":")),encoding="utf-8")

    # Also provide a human-readable report.
    report={
        "json":str(json_path),
        "atlas":str(atlas_path),
        "export_mode":"frame-swap-all-animations-optimized",
        "setup_animation":setup_anim_name,
        "setup_frame":int(setup_frame),
        "animations_exported":len(runtime_set),
        "animation_names":[str(e["name"]) for e,_,_ in runtime_set],
        "bones":1,
        "slots":len(slots),
        "mesh_attachments":total_attachments,
        "dedupe":bool(dedupe),
        "dedupe_tolerance":float(dedupe_tolerance),
        "dedupe_hits":dedupe_hits,
        "export_fps":export_fps,
        "frame_step":frame_step,
        "animations":animation_reports,
        "warnings":warnings,
    }
    (out/"spine_export_report.json").write_text(
        json.dumps(report,ensure_ascii=False,indent=2),
        encoding="utf-8"
    )
    return report

def bundle_to_spine_frame_swap_all(bundle_path,output_dir,setup_animation_name=None,
                                   setup_frame=0,name=None,include=None,exclude=None,
                                   data_animation=None,root_path_id=None,
                                   mesh_v_flip=False,show_hidden=False,dedupe=True,
                                   dedupe_tolerance=1e-4,export_fps=None,frame_step=None):
    out=Path(output_dir)
    extracted=out/"_extracted"

    manifest=extract_bundle(
        bundle_path,extracted,
        data_animation=data_animation,
        root_path_id=root_path_id,
        all_animations=True
    )

    entries=[]
    for item in manifest.get("all_animation_outputs",[]):
        entries.append({
            "index":item["index"],
            "name":item["name"],
            "animation_raw":str(extracted/item["animation_raw"])
        })

    entries=_filter_animation_entries(entries,include=include,exclude=exclude)
    if not entries:
        raise RuntimeError(
            f"No animations matched include={include!r}, exclude={exclude!r}"
        )

    if setup_animation_name and setup_animation_name not in [e["name"] for e in entries]:
        raise RuntimeError(
            f"Setup animation {setup_animation_name!r} was not selected. "
            f"Selected animations: {[e['name'] for e in entries]}"
        )

    result=export_spine_frame_swap_all(
        extracted/"parts_raw.json",
        entries,
        extracted/"cellmap.json",
        extracted/"textures",
        out,
        setup_animation_name=setup_animation_name,
        setup_frame=setup_frame,
        name=name or _safe(Path(bundle_path).stem),
        mesh_v_flip=mesh_v_flip,
        show_hidden=show_hidden,
        dedupe=dedupe,
        dedupe_tolerance=dedupe_tolerance,
        export_fps=export_fps,
        frame_step=frame_step
    )
    result["extract_manifest"]=str(extracted/"extract_manifest.json")
    return result
